name: CI

on:
  push:
    branches:
      - main
      - releases/*
  pull_request:
    branches:
      - '*'

env:
  CI: '1'

jobs:
  build:
    name: Node.js ${{ matrix.node_version }} on ${{ matrix.os }}
    if: always()
    concurrency:
      group: ${{ github.workflow }}-build-${{ matrix.os }}-${{ matrix.node_version }}-${{ github.ref }}
      cancel-in-progress: true
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        node_version: [14, 16, 18]
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    steps:
      - name: Setup repository
        uses: actions/checkout@v3
      - name: Setup environment
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node_version }}
      - name: Install dependencies
        run: npm install
      - name: Build package
        run: npm run build
      - name: Run hygiene checks
        run: npm run lint
      - name: Run unit tests
        run: npm run test
      - name: Run examples
        run: npm run example
